### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ItzStarlxy** [Mcbeany/Spyglass#5]
item not visible when held

**Comment by Mcbeany** [comment]
more details please

**Comment by LittleCutePM** [comment]
Here some detail

Pada tanggal Sel, 21 Sep 2021 20.13, Khang Nguyen ***@***.***>
menulis:

**Comment by LittleCutePM** [comment]
![Uploading Screenshot_2021-09-21-20-24-50-32.png…]()

**Comment by ItzStarlxy** [comment]
![Screenshot_2021-09-21-20-24-50-32](https://user-images.githubusercontent.com/79429172/134170886-49e0454d-912c-40c1-94a3-fbef2fe7a232.png)

**Comment by Mcbeany** [comment]
thanks, i will fix it
