### ISSUE TITLE
Item duplicate

### ISSUE THREAD

**Issue by ItzStarlxy** [Mcbeany/Spyglass#6]
![IMG-20210930-WA0432](https://user-images.githubusercontent.com/79429172/135403785-741edd02-3965-45e0-af68-aa83de544344.jpg)
Item is duplicate

**Comment by Mcbeany** [comment]
more details please

**Comment by Mcbeany** [comment]
![image](https://user-images.githubusercontent.com/77101686/135404325-cd4c3281-04bf-46cb-bce7-8543d019b6a4.png)
![image](https://user-images.githubusercontent.com/77101686/135404358-2a3950cd-e918-4523-b744-3169f28d9294.png)
